---
- name: Apply ufw rules
  ufw:
    rule: "{{ item.rule }}"
    from: "{{ item.from }}"
    port: "{{ item.port }}"
    state: "{{ item.state }}"
    proto: "{{ item.proto}}"
  loop: "{{ ufw.rules }}"